name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - name: Crear Vue Config
      run: mv pages_config.js vue.config.js
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'pedroprieto'
        reponame: 'dwec_u07_cpe'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged

